// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";

/// @notice Shared Halo2 proof fixtures generated by `scripts/build_zk_artifacts.sh`.
abstract contract Halo2FixtureTest is Test {
    using stdJson for string;

    bytes internal fixtureProof;
    uint256[] internal fixturePublicInputs;
    bytes32 internal fixtureModelCommitment;
    uint256 internal fixtureCommitmentField;

    function setUp() public virtual {
        string memory root = vm.projectRoot();
        string memory bundlePath = string.concat(root, "/test/fixtures/proof_bundle.json");
        string memory witnessPath = string.concat(root, "/test/fixtures/witness.json");
        string memory bundle = vm.readFile(bundlePath);
        string memory witness = vm.readFile(witnessPath);

        fixtureProof = vm.parseJsonBytes(bundle, ".proof_hex");
        fixturePublicInputs = new uint256[](3);
        fixturePublicInputs[0] = bundle.readUint(".public_inputs[0]");
        fixturePublicInputs[1] = bundle.readUint(".public_inputs[1]");
        fixturePublicInputs[2] = bundle.readUint(".public_inputs[2]");
        fixtureModelCommitment = vm.parseJsonBytes32(witness, ".model_commitment");
        fixtureCommitmentField = fixturePublicInputs[2];
    }
}
