"use client";

import Image from "next/image";
import { motion } from "framer-motion";
import { Fingerprint, ShieldCheck, Sigma } from "lucide-react";

const stages = [
  {
    index: "01",
    icon: Fingerprint,
    title: "KZG commitments",
    body: "Quantized model weights are committed with the Ethereum ceremony SRS via py_ecc, then registered on-chain per agent.",
  },
  {
    index: "02",
    icon: Sigma,
    title: "Halo2 proofs",
    body: "A fixed-topology MLP circuit proves inference and safety public inputs. Proofs are generated by the Rust prover-core crate.",
  },
  {
    index: "03",
    icon: ShieldCheck,
    title: "On-chain enforcement",
    body: "TrustMeshVerifier validates the proof, applies SafetyInterceptor rules, executes allowlisted calls, and emits a VerifiedDecision event.",
  },
];

const snippet = `function verifyAndExecute(
    bytes calldata proof,
    bytes32 commitment,
    Action calldata action
) external {
    require(
        halo2Verifier.verify(proof, commitment, action.publicInputs),
        "invalid proof"
    );
    safetyInterceptor.check(action);
    _execute(action);
    emit VerifiedDecision(commitment, action.hash());
}`;

export function SecurityCryptography() {
  return (
    <section
      id="security"
      className="border-t border-zinc-900 bg-zinc-950/40"
    >
      <div className="mx-auto max-w-6xl px-6 py-28">
        <div className="mx-auto max-w-2xl text-center">
          <p className="font-mono text-xs uppercase tracking-widest text-emerald-500">
            security & cryptography
          </p>
          <h2 className="mt-4 text-balance text-3xl font-semibold tracking-tight text-zinc-50 sm:text-4xl">
            Nothing to trust. Everything to verify.
          </h2>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-80px" }}
          transition={{ duration: 0.6 }}
          className="relative mx-auto mt-14 aspect-[1376/768] w-full max-w-3xl overflow-hidden rounded-2xl border border-emerald-500/15 bg-zinc-950/60 shadow-[0_0_60px_-24px_rgba(16,185,129,0.35)]"
        >
          <Image
            alt="A shield-shaped verification core processing encrypted, hashed, and signed data into a zero-knowledge proof, illustrating how TrustMesh verifies inference without revealing the underlying model"
            src="/images/zk-verification.png"
            fill
            loading="lazy"
            sizes="(min-width: 1024px) 768px, 92vw"
            className="object-cover"
          />
        </motion.div>

        <div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-800 md:grid-cols-3">
          {stages.map((stage, i) => (
            <motion.div
              key={stage.index}
              initial={{ opacity: 0, y: 14 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1, duration: 0.5 }}
              className="group relative bg-zinc-950 p-7 transition-colors hover:bg-zinc-900/80"
            >
              <span className="absolute right-5 top-5 font-mono text-4xl font-semibold text-zinc-800 transition-colors group-hover:text-emerald-500/20">
                {stage.index}
              </span>
              <div className="flex h-10 w-10 items-center justify-center rounded-lg border border-emerald-500/20 bg-emerald-500/10 text-emerald-400">
                <stage.icon className="h-5 w-5" />
              </div>
              <h3 className="mt-5 text-base font-semibold text-zinc-100">
                {stage.title}
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-zinc-400">
                {stage.body}
              </p>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="mt-6 overflow-hidden rounded-2xl border border-zinc-800/80 bg-zinc-950"
        >
          <div className="flex items-center justify-between border-b border-zinc-800/80 px-5 py-3">
            <span className="font-mono text-xs text-zinc-500">
              TrustMeshVerifier.sol
            </span>
            <span className="flex gap-1.5">
              <span className="h-2.5 w-2.5 rounded-full bg-zinc-800" />
              <span className="h-2.5 w-2.5 rounded-full bg-zinc-800" />
              <span className="h-2.5 w-2.5 rounded-full bg-emerald-500/50" />
            </span>
          </div>
          <pre className="overflow-x-auto px-5 py-5 font-mono text-[13px] leading-relaxed text-zinc-300">
            <code>{snippet}</code>
          </pre>
        </motion.div>
      </div>
    </section>
  );
}