"use client";

import Link from "next/link";
import { ArrowRight, Code2, Fingerprint, ShieldCheck, Sigma } from "lucide-react";

import { AppNav } from "@/components/AppNav";
import { ArchitectureDiagram } from "@/components/ArchitectureDiagram";
import { PageShell, sectionLabel } from "@/components/PageShell";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const stages = [
  {
    index: "01",
    icon: Fingerprint,
    title: "KZG commitments",
    body: "Quantized model weights are committed with Ethereum ceremony SRS via py_ecc. Bindings are registered on-chain per agent.",
  },
  {
    index: "02",
    icon: Sigma,
    title: "Halo2 proofs",
    body: "A fixed-topology MLP circuit proves inference and safety public inputs. Proofs are generated by the Rust prover-core crate.",
  },
  {
    index: "03",
    icon: ShieldCheck,
    title: "On-chain enforcement",
    body: "TrustMeshVerifier validates proofs, applies SafetyInterceptor rules, executes allowlisted calls, and emits VerifiedDecision audit events.",
  },
];

const workflow = [
  "Register agent with KZG model commitment",
  "Observe market data and run inference",
  "Generate Halo2 witness and proof",
  "Submit verifyAndExecute on Sepolia",
  "Execute allowlisted DeFi payload",
  "Stream VerifiedDecision to dashboard / LangChain",
];

export default function LandingPage() {
  return (
    <PageShell>
      <AppNav />

      <main className="mx-auto max-w-6xl px-6 py-16">
        {/* Hero */}
        <section className="grid gap-14 lg:grid-cols-2 lg:items-center">
          <div className="space-y-7">
            <div className="flex flex-wrap items-center gap-3">
              <span className="inline-flex items-center gap-2 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-1 font-mono text-xs text-emerald-400">
                <span className="relative flex h-1.5 w-1.5">
                  <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75" />
                  <span className="relative inline-flex h-1.5 w-1.5 rounded-full bg-emerald-400" />
                </span>
                sepolia · live
              </span>
              <span className="font-mono text-xs uppercase tracking-widest text-zinc-500">
                verifiable ai for defi agents
              </span>
            </div>

            <h1 className="text-4xl font-semibold leading-[1.1] tracking-tight text-zinc-50 sm:text-5xl">
              TrustMesh binds model commitments,{" "}
              <span className="bg-gradient-to-r from-emerald-300 to-emerald-500 bg-clip-text text-transparent">
                zero-knowledge proofs
              </span>
              , and on-chain safety rules.
            </h1>

            <p className="max-w-xl text-lg leading-relaxed text-zinc-400">
              Agents register a KZG model commitment, prove inference outcomes with Halo2, and
              submit verified actions to Ethereum. Safety constraints enforce liquidity,
              concentration, registry, and velocity limits before execution.
            </p>

            <div className="flex flex-wrap gap-3 pt-1">
              <Button
                asChild
                className="bg-emerald-500 text-emerald-950 shadow-[0_0_24px_-6px_rgba(52,211,153,0.6)] hover:bg-emerald-400"
              >
                <Link href="/dashboard">
                  Launch demo dashboard
                  <ArrowRight className="ml-1.5 h-4 w-4" />
                </Link>
              </Button>
              <Button
                asChild
                variant="outline"
                className="border-zinc-700 bg-transparent text-zinc-200 hover:border-emerald-500/50 hover:bg-emerald-500/5 hover:text-emerald-300"
              >
                <Link href="/about">Read architecture</Link>
              </Button>
              <Button asChild variant="ghost" className="text-zinc-400 hover:bg-zinc-900 hover:text-zinc-100">
                <a href="https://github.com" rel="noreferrer" target="_blank">
                  <Code2 className="mr-1.5 h-4 w-4" />
                  GitHub
                </a>
              </Button>
            </div>
          </div>

          <div className="relative">
            <div className="absolute -inset-4 rounded-3xl bg-emerald-500/10 blur-2xl" />
            <div className="relative rounded-2xl border border-emerald-500/15 bg-zinc-900/60 p-2 backdrop-blur">
              <ArchitectureDiagram />
            </div>
          </div>
        </section>

        {/* Pipeline stages */}
        <section className="mt-28">
          <p className={sectionLabel}>the pipeline</p>
          <div className="mt-4 grid gap-px overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-800 md:grid-cols-3">
            {stages.map((stage) => (
              <div
                key={stage.index}
                className="group relative bg-zinc-950 p-7 transition-colors hover:bg-zinc-900/80"
              >
                <span className="absolute right-5 top-5 font-mono text-4xl font-semibold text-zinc-800 transition-colors group-hover:text-emerald-500/20">
                  {stage.index}
                </span>
                <div className="flex h-10 w-10 items-center justify-center rounded-lg border border-emerald-500/20 bg-emerald-500/10 text-emerald-400">
                  <stage.icon className="h-5 w-5" />
                </div>
                <h3 className="mt-5 text-base font-semibold text-zinc-100">
                  Stage {stage.index} — {stage.title}
                </h3>
                <p className="mt-2 text-sm leading-relaxed text-zinc-400">{stage.body}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Interactive workflow */}
        <section className="mt-24 rounded-2xl border border-zinc-800 bg-zinc-900/40 p-8">
          <div className="flex items-baseline justify-between gap-4">
            <h2 className="text-lg font-semibold text-zinc-100">Interactive workflow</h2>
            <span className="font-mono text-xs text-zinc-500">6 steps · end to end</span>
          </div>

          <ol className="mt-6 grid gap-x-10 gap-y-5 md:grid-cols-2">
            {workflow.map((step, i) => (
              <li key={step} className="flex items-start gap-3">
                <span
                  className={cn(
                    "mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border font-mono text-[11px]",
                    "border-emerald-500/30 bg-emerald-500/10 text-emerald-400",
                  )}
                >
                  {i + 1}
                </span>
                <span className="text-sm leading-relaxed text-zinc-300">{step}</span>
              </li>
            ))}
          </ol>
        </section>
      </main>
    </PageShell>
  );
}
