"use client";

import Link from "next/link";

import { AppNav } from "@/components/AppNav";
import { ArchitectureDiagram } from "@/components/ArchitectureDiagram";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background">
      <AppNav />
      <main className="mx-auto max-w-6xl px-6 py-16">
        <section className="grid gap-10 lg:grid-cols-2 lg:items-center">
          <div className="space-y-6">
            <p className="text-sm font-medium uppercase tracking-wide text-primary">
              Verifiable AI for DeFi agents
            </p>
            <h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">
              TrustMesh binds model commitments, zero-knowledge proofs, and on-chain safety rules.
            </h1>
            <p className="text-lg text-muted-foreground">
              Agents register a KZG model commitment, prove inference outcomes with Halo2, and
              submit verified actions to Ethereum. Safety constraints enforce liquidity, concentration,
              registry, and velocity limits before execution.
            </p>
            <div className="flex flex-wrap gap-3">
              <Button asChild>
                <Link href="/dashboard">Launch demo dashboard</Link>
              </Button>
              <Button asChild variant="outline">
                <Link href="/about">Read architecture</Link>
              </Button>
              <Button asChild variant="ghost">
                <a href="https://github.com" rel="noreferrer" target="_blank">
                  GitHub
                </a>
              </Button>
            </div>
          </div>
          <ArchitectureDiagram />
        </section>

        <section className="mt-20 grid gap-6 md:grid-cols-3">
          {[
            {
              title: "Stage 1 — KZG commitments",
              body: "Quantized model weights are committed with Ethereum ceremony SRS via py_ecc. Bindings are registered on-chain per agent.",
            },
            {
              title: "Stage 2 — Halo2 proofs",
              body: "A fixed-topology MLP circuit proves inference and safety public inputs. Proofs are generated by the Rust prover-core crate.",
            },
            {
              title: "Stage 3 — On-chain enforcement",
              body: "TrustMeshVerifier validates proofs, applies SafetyInterceptor rules, executes allowlisted calls, and emits VerifiedDecision audit events.",
            },
          ].map((item) => (
            <Card key={item.title}>
              <CardHeader>
                <CardTitle className="text-base">{item.title}</CardTitle>
                <CardDescription>{item.body}</CardDescription>
              </CardHeader>
            </Card>
          ))}
        </section>

        <Card className="mt-20">
          <CardHeader>
            <CardTitle>Interactive workflow</CardTitle>
          </CardHeader>
          <CardContent>
            <ol className="grid gap-3 text-sm text-muted-foreground md:grid-cols-2">
              <li>1. Register agent with KZG model commitment</li>
              <li>2. Observe market data and run inference</li>
              <li>3. Generate Halo2 witness and proof</li>
              <li>4. Submit verifyAndExecute on Sepolia</li>
              <li>5. Execute allowlisted DeFi payload</li>
              <li>6. Stream VerifiedDecision to dashboard / LangChain</li>
            </ol>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}
